[project]
name = "rctiplus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.5",
    "httpx>=0.28.0",
    "m3u8>=6.0.0",
]

